import 'package:shoppingappsampleflutter/core/models/product.dart';

const List<Product> sampleProducts1 = [
  Product(
    id: "1",
    name:
        "QiCheng&LYS Teddy Bomei Winter Clothing, clothes for pets,Pet Dog Warm Jacket, Small Dog Winter Clothes,dogs tracksuit(XL, Blue)",
    price: 6.99,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/51Ie2GNIeyL._AC_UL320_.jpg",
      "lib/core/services/api/sample_data/assets/71ZxkyZPZcL._AC_SL1200_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "2",
    name: "Jack & Jones Men's Jjecorp Logo Tee Ss Crew Neck Noos T-Shirt",
    price: 26.51,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/81aWpazNFdL._AC_UX466_.jpg",
      "lib/core/services/api/sample_data/assets/81E46LhxkcL._AC_UX569_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "3",
    name: "Merrell Women's Siren 3 Low Rise Trainers",
    price: 190.51,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/81eFza8dcnL._AC_UX695_.jpg",
      "lib/core/services/api/sample_data/assets/81ljG5Nx+5L._AC_UX500_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "4",
    name:
        "QiCheng&LYS Teddy Bomei Winter Clothing, clothes for pets,Pet Dog Warm Jacket, Small Dog Winter Clothes,dogs tracksuit(XL, Blue)",
    price: 6.99,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/51Ie2GNIeyL._AC_UL320_.jpg",
      "lib/core/services/api/sample_data/assets/71ZxkyZPZcL._AC_SL1200_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "5",
    name: "Jack & Jones Men's Jjecorp Logo Tee Ss Crew Neck Noos T-Shirt",
    price: 26.51,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/81aWpazNFdL._AC_UX466_.jpg",
      "lib/core/services/api/sample_data/assets/81E46LhxkcL._AC_UX569_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "6",
    name: "Merrell Women's Siren 3 Low Rise Trainers",
    price: 190.51,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/81eFza8dcnL._AC_UX695_.jpg",
      "lib/core/services/api/sample_data/assets/81ljG5Nx+5L._AC_UX500_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "7",
    name:
        "QiCheng&LYS Teddy Bomei Winter Clothing, clothes for pets,Pet Dog Warm Jacket, Small Dog Winter Clothes,dogs tracksuit(XL, Blue)",
    price: 6.99,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/51Ie2GNIeyL._AC_UL320_.jpg",
      "lib/core/services/api/sample_data/assets/71ZxkyZPZcL._AC_SL1200_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "8",
    name: "Jack & Jones Men's Jjecorp Logo Tee Ss Crew Neck Noos T-Shirt",
    price: 26.51,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/81aWpazNFdL._AC_UX466_.jpg",
      "lib/core/services/api/sample_data/assets/81E46LhxkcL._AC_UX569_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "9",
    name: "Merrell Women's Siren 3 Low Rise Trainers",
    price: 190.51,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/81eFza8dcnL._AC_UX695_.jpg",
      "lib/core/services/api/sample_data/assets/81ljG5Nx+5L._AC_UX500_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "10",
    name:
        "QiCheng&LYS Teddy Bomei Winter Clothing, clothes for pets,Pet Dog Warm Jacket, Small Dog Winter Clothes,dogs tracksuit(XL, Blue)",
    price: 6.99,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/51Ie2GNIeyL._AC_UL320_.jpg",
      "lib/core/services/api/sample_data/assets/71ZxkyZPZcL._AC_SL1200_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "11",
    name: "Jack & Jones Men's Jjecorp Logo Tee Ss Crew Neck Noos T-Shirt",
    price: 26.51,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/81aWpazNFdL._AC_UX466_.jpg",
      "lib/core/services/api/sample_data/assets/81E46LhxkcL._AC_UX569_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
  Product(
    id: "12",
    name: "Merrell Women's Siren 3 Low Rise Trainers",
    price: 190.51,
    photoAssets: [
      "lib/core/services/api/sample_data/assets/81eFza8dcnL._AC_UX695_.jpg",
      "lib/core/services/api/sample_data/assets/81ljG5Nx+5L._AC_UX500_.jpg",
    ],
    specifications: [
      "The stormbreak is waterproof over trouser",
      "Designed with outside fun in mind",
      "100% Polyester",
      "Trousers",
      "W808",
      "Using our tough wearing hydrafort fabric with fully taped seams",
      "Press stud hems and an elasticated waist",
      "Protect from both wind and rain",
    ],
  ),
];
